# Generated by Django 5.0.6 on 2024-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
