# Generated by Django 5.0.6 on 2024-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_body2_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_color',
            field=models.CharField(default='#00bd91', max_length=10),
        ),
    ]
